### ISSUE TITLE
Deleted entries and custom fields re-appearing after a while (WebDAV)

### ISSUE THREAD

**Issue by smxsm** [buttercup/buttercup#202] opened 2017-04-05 08:32 UTC
Hi, I have a strange issue, using Buttercup 0.11.1-alpha with a WebDAV-Server - after a while and various restarts, old and already deleted entries, folders and/or custom fields are re-appearing in the app. So, I have e.g. four custom fields for an entry which were deleted either one or two days ago and which have been away for at least a day - but now they are back. I also have some folders in the "Trash", although I have already clicked "Empty trash" at least twice since deleting those entries ....
I am pretty much the only person actively using this WebDAV server at the moment, so I have no idea where those "ghost" entries are coming from... any idea? Thanks!

**Comment by perry-mitchell** [comment] 2017-04-06 19:50
Hi @smxsm - This sounds like you're getting overwritten copies (old versions) of your archive coming through. To confirm, you're using buttercup GUI and saving files in a webdav sync'd directory, right?

I suspect that your webdav server may either be reverting to old file versions or is completely disregarding your updated copies (saves) and just overwriting them with old copies from the server. You could try saving several times and checking the file size/contents locally and remotely to ensure that the changes are making it to the server.

**Comment by smxsm** [comment] 2017-04-06 20:36
Hi, thanks for the answer! The files seem to be in sync and the server file is updated when I save... but there was a .DAV folder on the server which had an older "bcup" file in it -  I have deleted the folder now and until now (5 restarts) I've had no old data in the Buttercup app ... fingers crossed :)
I hope it doesn't come back again ....

**Comment by smxsm** [comment] 2017-04-07 07:46
hm, nope, now it happened again, and there is no new ".DAV" folder on the webdav server ... and the .bcup file on the server has the timestamp from my last save yesterday, so everything *seems* to be ok file-wise... any other idea? :(

**Comment by smxsm** [comment] 2017-04-07 11:15
Just to add, it's not really that the archive is an old version from day X, if I've added new entries e.g., they are still available and up-to-date ... it's just that (sometimes) already deleted entries, folders or custom values keep coming back like zombies :P

**Comment by perry-mitchell** [comment] 2017-04-07 14:23
> already deleted entries, folders or custom values keep coming back like zombies

Your case is interesting for sure. At this stage I'd still lean towards the issue being with WebDAV, however, as it seems more likely that it's overwriting your local copy.

What you could try to do it copy the file **out** of your webdav directory and put it somewhere static. Load and save it from there for some time and see if the issue still occurs - my guess is that it probably doesn't - but I'm open minded.

Let's go from there so we can rule some things out 🙂

**Comment by smxsm** [comment] 2017-04-07 14:48
Hm, until now everything looks good if I copy the file locally... so it seems to be a problem with the WebDAV communication - but I couldn't find any similar problems with WebDAV or any advice on the net how to configure a WebDAV server to handle problems like this. Do you have any suggestion what I could try on the server to get rid of this? I am running Apache/2.2.22 (Ubuntu) with WebDav module. My Buttercup client is running on a Macbook.
Anything I could try to debug the Buttercup WebDAV / archive usage? I also have my own Buttercup build, so I could add some debug code and build me a new debug version :)

**Comment by smxsm** [comment] 2017-04-10 15:31
Unsurprisingly, same on Windows .... so it really seems to be an issue with Buttercup and WebDAV - any idea? Do you know if anybody is using WebDAV with buttercup successfully? Thanks :)

**Comment by perry-mitchell** [comment] 2017-04-10 20:12
> Buttercup and WebDAV

I agree that it looks funny here, but if you using a sync client then Buttercup doesn't have much to do with it. It writes to a file and reads from it in a very simple manner.

That being said - @sallar can you think of any peculiarities with our saving system in the GUI? The filesystem has always been a bit more custom here and just want to make sure that we're not missing some complexity here that might behave differently in this scenario..

**Comment by smxsm** [comment] 2017-04-12 12:35
Ha, I've just tried the new 0.12 version with the direct Cloud integration and opened the WebDAV file directly - now the zombies are gone, after I have deleted them once! :) So it looks like it was only a problem with accessing the file via Windows Explorer or MAC Finder.

**Comment by perry-mitchell** [comment] 2017-04-12 13:30
> So it looks like it was only a problem with accessing the file via Windows Explorer or MAC Finder.

I really hope so. Let us know if it's still reoccurring.

**Comment by sallar** [comment] 2017-04-13 07:05
@smxsm @perry-mitchell I'm going to go ahead and close this for now as it seems the new cloud access has solved this issue. If the problem comes back, please do re-open this issue 👍 Thanks

**Comment by smxsm** [comment] 2017-04-13 07:12
Oh no, I've just tried one more time today and guess what ... the zombies are back :( All the changes I've made yesterday are there, so the archive itself is "up-to-date", but there are entries and folders in the trash and also long deleted custom fields in some entries. E.g. the "TestToDelete" folder was deleted and removed from trash at least one week ago :P And the trash was empty yesterday evening...
![image](https://cloud.githubusercontent.com/assets/1737182/24993990/2425906c-2029-11e7-82c4-388aba17e38b.png)
How can this be possible at all? Magic? :)

**Comment by perry-mitchell** [comment] 2017-04-13 08:37
Sorry to hear @smxsm. Currently it definitely looks like an issue with your WebDAV synchronisation - We can't really affect that with Buttercup so at this stage there's probably no issue with the desktop application.

We'll keep an eye on the webdav sync during our regular testing and will obviously let you know if we see anything of concern. If you do happen to discover what's causing the issue please don't hesitate in filing another issue..

**Comment by smxsm** [comment] 2017-04-13 13:07
What I did now is:
* rename the archive file on the server
* removed the Port 80 vhost entry and only left the 443 entry active for the webdav subdomain
* installed ntp to sync the server time with a ntp server

**Until now**, it is working .... ;) If the zombies come back, I am out of ideas though ... and may switch to Owncloud :)

**Comment by perry-mitchell** [comment] 2017-04-16 13:49
Seems that we've been able to reproduce this, though mostly just with trash:

![image](https://cloud.githubusercontent.com/assets/3869469/25071610/94657f16-22c4-11e7-9d4f-2df19475c3e6.png)

^ I've emptied the trash several times, so there seems to be some load issue coupled with webdav possibly.

**Comment by perry-mitchell** [comment] 2017-04-16 13:58
Seems that trash is completely impossible to empty 😅

**Closed** 2017-04-16 17:25 UTC
Labels: Priority: Critical, Status: Available, Type: Bug

**Comment by perry-mitchell** [comment] 2017-04-16 18:44
@smxsm please try the latest version - hopefully we've weeded out the weirdness. There's still some updates to come which may affect your case (#219), but this one should help immensely.

**Comment by smxsm** [comment] 2017-04-16 20:53
Nice 👍  I've updated and I'll let you know if I can see the zombies again :)

**Comment by georglauterbach** [comment] 2023-12-19 18:57
Sorry to revive this old issue (speaking of zombies, haha), but I see the very same thing. I am also using WebDAV for the browser plugin, and I am syncing the file via NextCloud. To make matters worse, when I edit the name of a field (not even deleting it), the old name re-appears next to the new name.. this is **extremely annoying**. @perry-mitchell please tell me which information you require. Shall I open a new issue for this?

**Comment by georglauterbach** [comment] 2023-12-21 21:17
This has become super-annoyoing now. @perry-mitchell what can we do about this? I can literally not really edit entries, because old ones keep coming back as soon as I edit the entry again..
